package uk.gov.companieshouse.efs.api.events.service.fesloader;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.testcontainers.junit.jupiter.Testcontainers;
import uk.gov.companieshouse.efs.api.events.service.model.FormModel;
import uk.gov.companieshouse.efs.api.util.OracleTestContainer;

@Testcontainers
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class FormDaoITest {
    static JdbcTemplate jdbcTemplate;
    static FormDao formDao;

    @BeforeAll
    static void setUpFormDao() {
        jdbcTemplate = new JdbcTemplate(
            new DriverManagerDataSource(
                OracleTestContainer.INSTANCE.getJdbcUrl(),
                OracleTestContainer.INSTANCE.getUsername(),
                OracleTestContainer.INSTANCE.getPassword()
            )
        );
        jdbcTemplate.execute("""
            CREATE TABLE form (
                FORM_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                FORM_BARCODE VARCHAR2(8),
                FORM_INCORPORATION_NUMBER VARCHAR2(8),
                FORM_CORPORATE_BODY_NAME VARCHAR2(160),
                FORM_TYPE VARCHAR2(30),
                FORM_IMAGE_ID NUMBER(10),
                FORM_ENVELOPE_ID NUMBER(10),
                FORM_STATUS NUMBER(10),
                FORM_PAGE_COUNT NUMBER(4),
                FORM_OCR_FORM_TYPE VARCHAR2(20),
                FORM_OCR_CORPORATE_BODY_NAME VARCHAR2(160),
                FORM_OCR_INCORPORATION_NUMBER VARCHAR2(8),
                FORM_OCR_BARCODE_1 VARCHAR2(20),
                FORM_BARCODE_DATE DATE,
                FORM_SAME_DAY VARCHAR2(1)
            )
        """);
        jdbcTemplate.execute("CREATE SEQUENCE FORM_ID_SEQ START WITH 1 INCREMENT BY 1");
        formDao = new FormDao(jdbcTemplate);
    }

    @Test
    void insertForm_insertsRow() {
        final var model = FormModel.builder()
            .withBarcode("123456")
            .withCompanyNumber("COMP123")
            .withCompanyName("Test Company")
            .withFormType("TYPE1")
            .withImageId(1L)
            .withEnvelopeId(2L)
            .withFormStatus(3L)
            .withNumberOfPages(1)
            .withBarcodeDate(java.time.LocalDateTime.of(2024, 1, 1, 0, 0))
            .withSameDayService(false)
            .build();

        formDao.insertForm(model);

        final var verifyQuery = """
            SELECT FORM_BARCODE,
                   FORM_INCORPORATION_NUMBER,
                   FORM_CORPORATE_BODY_NAME,
                   FORM_TYPE,
                   FORM_IMAGE_ID,
                   FORM_ENVELOPE_ID,
                   FORM_STATUS,
                   FORM_PAGE_COUNT,
                   FORM_BARCODE_DATE,
                   FORM_SAME_DAY
            FROM form
            WHERE FORM_BARCODE = ?
        """;

        var rowCount = new AtomicInteger();
        jdbcTemplate.query(verifyQuery,
            rs -> {
                rowCount.incrementAndGet();
                assertThat(rs.getString("FORM_BARCODE"), is("123456"));
                assertThat(rs.getString("FORM_INCORPORATION_NUMBER"), is("COMP123"));
                assertThat(rs.getString("FORM_CORPORATE_BODY_NAME"), is("Test Company"));
                assertThat(rs.getString("FORM_TYPE"), is("TYPE1"));
                assertThat(rs.getString("FORM_IMAGE_ID"), is("1"));
                assertThat(rs.getString("FORM_ENVELOPE_ID"), is("2"));
                assertThat(rs.getString("FORM_STATUS"), is("3"));
                assertThat(rs.getInt("FORM_PAGE_COUNT"), is(1));
                assertThat(rs.getTimestamp("FORM_BARCODE_DATE"), is(java.sql.Timestamp.valueOf("2024-01-01 00:00:00")));
                assertThat(rs.getString("FORM_SAME_DAY"), is("N"));
            }, "123456");
        assertThat(rowCount.get(), is(1));
    }
}

